### ISSUE TITLE
devtools::install_github("mcjmigdal/xcoredata@r4_1") doesn't work

### ISSUE THREAD

**Issue by bkaczkowski** [bkaczkowski/xcore#20]
Hi @mcjmigdal, 

devtools::install_github("mcjmigdal/xcoredata@r4_1")  gives following  error:

snapshotDate(): 2021-10-19
Error: package or namespace load failed for ‘xcoredata’:
 .onLoad failed in loadNamespace() for 'xcoredata', details:
  call: FUN(X[[i]], ...)
  error: ‘chip_atlas_meta’ not found in ExperimentHub
Error: loading failed
Execution halted

**Comment by mcjmigdal** [comment]
@bkaczkowski right... this should be fixed now. However, for R4.1 we can't use ExperimentHub infrastructure so instead we host signatures files using Git LFS. Unfortunately, I've already run out of my bandwidth and I can't push the updates to Github. The bandwidth resets in a week. For now I've imported xcoredata to Gitlab and pushed the fix there.

Please install xcoredata from there using

`devtools::install_gitlab("mcjmigdal/xcoredata@r4_1")`

I will update the README in xcore to use this command as well.

**Comment by bkaczkowski** [comment]
Thanks! It works now!
