### ISSUE TITLE
Error in loadNamespace(x) : there is no package called ‘pheatmap’

### ISSUE THREAD

**Issue by bkaczkowski** [bkaczkowski/xcore#22]
Error in loadNamespace(x) : there is no package called ‘pheatmap’

**Comment by mcjmigdal** [comment]
@bkaczkowski you need to install `pheatmap` package. 

We only use `pheatmap` package in the vignette as `xcore` provide no plotting functionality. `pheatmap` is properly included in DESCRIPTION file as suggested package. I believe you opened this issue asking to make `pheatmap` an imported package such that it automatically install when installing `xcore` using `devtools`. However, I think the way it is now is as it should be and it is up to user to install `pheatmap`. Limiting the number of dependencies is always describable.

**Comment by bkaczkowski** [comment]
ok it's not bug for the xcore, but it is an issue for the vignette as the error occurs (for less experience users). I added "library(pheatmap" so the library is loaded, and if the user doesn't have it installed they will get clear error
